sudo: required
services:
  - docker

before_install:
  - docker build -t janneleppanen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run janneleppanen/react-test npm test -- --coverage

after_success:
  - docker build -t janneleppanen/multi-client ./client
  - docker build -t janneleppanen/multi-nginx ./nginx
  - docker build -t janneleppanen/multi-server ./server
  - docker build -t janneleppanen/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push janneleppanen/multi-client
  - docker push janneleppanen/multi-nginx
  - docker push janneleppanen/multi-server
  - docker push janneleppanen/multi-worker
